-- AlterTable
ALTER TABLE "tasks" ADD COLUMN     "pageDurationFrom" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "pageDurationTo" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN     "pagesDepthFrom" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "pagesDepthTo" INTEGER NOT NULL DEFAULT 5;
